CREATE TABLE providers(
    provider_id VARCHAR(255) PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL UNIQUE,
    bio TEXT,
    ratings_average INT(11) DEFAULT 0,
    reviews_count INT(11) DEFAULT 0,
    services_count INT(11) DEFAULT 0,
    jobs_count INT(11) DEFAULT 0,
    portfolio_count INT(11) DEFAULT 0,
    price BIGINT(20),
    currency CHAR(3) DEFAULT 'KES',
    category_id INT(20),
    industry_id INT(20),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    deleted_at DATETIME DEFAULT NULL,
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    FOREIGN KEY (category_id) REFERENCES categories(id),
    FOREIGN KEY (industry_id) REFERENCES industries(id)
);